
meta_product_name: "LEALO"
meta_title: "LEALO | Learn Locally"
meta_description: "Discover and match with nearby teachers so you can learn locally."
meta_image: "https://images.unsplash.com/photo-1503564996084-7acb58ec325c?auto=format&fit=crop&w=750&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D"

